Adicionando lucro dos rendimentos por mês
andreroggeri/pynubank pull request #233
Opened 2021-04-30 19:18 UTC by Ulisses1478

Não cheguei a somar todos os valores para ver se bate certinho mas a api está disponível, talvez precise de alguns ajustes não consegui fazer o pytest dar certo sem puxar o inspect._empty na função.

2021-06-02 17:44 UTC, andreroggeri requested changes

2021-06-02 17:44 UTC, andreroggeri commented on pynubank/nubank.py
> +    def get_account_investments_yield(self, month=datetime.datetime.now().month, year=datetime.datetime.now().year) -> float:
Poderiamos simplificar e receber só um objeto do tipo datetime ? (Mantendo o padrão como now)

2021-06-02 17:44 UTC, andreroggeri commented on pynubank/nubank.py
> +        if isinstance(month, inspect._empty) or isinstance(year, inspect._empty):
Não gosto muito da ideia de utilizar esse `_empty` por ser uma variavel privada e pode mudar no futuro.

Estou pensando aqui se essa verificação realmente é necessária, pois nos outros métodos não validamos as entradas

2021-06-02 17:44 UTC, andreroggeri commented on pynubank/nubank.py
> +        return float(''.join(num for num in value if num.isdigit() or num == '.'))
Para essa lógica de extração do valor para float poderia jogar em um util ? Assim poderiamos em fazer o mesmo para transações que não tem o valor declarado e poderia reutilizar.

Poderia ser algo do tipo:
 - Remover R$
 - Limpar os espaços em branco
 - Substituir . por nada
 - Substituir , por .
 - float() no que sobrou

2021-06-02 17:56 UTC, Ulisses1478 commented on pynubank/nubank.py
> +        if isinstance(month, inspect._empty) or isinstance(year, inspect._empty):
No empty, eu não tive uma opção eu tentei fazer funcionar sem ele também não entendi pra que ele serve como você faria?

2021-06-02 17:57 UTC, Ulisses1478 commented on pynubank/nubank.py
> +        return float(''.join(num for num in value if num.isdigit() or num == '.'))
A parte ruim disso é que qualquer modificação na maneira em que o nubank entrega os dados ia gerar um erro

2021-06-02 17:59 UTC, Ulisses1478 commented on pynubank/nubank.py
> +    def get_account_investments_yield(self, month=datetime.datetime.now().month, year=datetime.datetime.now().year) -> float:
Irei simplificar mas deixei dessa maneira porque acredito dar mais trabalho criar um datetime dependendo do fluxo de quem está programando do que dar apenas esses 2 valores, mas é algo de preferência não faz diferença pra mim.

2021-06-02 18:09 UTC, Ulisses1478 commented on pynubank/nubank.py
> +        if isinstance(month, inspect._empty) or isinstance(year, inspect._empty):
Eu não consigo invocar no caso nem o .month do objeto datetime nem o .year por causa que ele me retorna
Mas acredito que seja algo do teste não da função em si
```
AttributeError: '_empty' object has no attribute 'year'
```

2021-06-02 18:10 UTC, andreroggeri commented on pynubank/nubank.py
> +        return float(''.join(num for num in value if num.isdigit() or num == '.'))
Sim, mas isso já pode acontecer aqui né ?

2021-06-02 18:12 UTC, Ulisses1478 commented on pynubank/nubank.py
> +        return float(''.join(num for num in value if num.isdigit() or num == '.'))
Sim, pode mas pensei ser mais provável adicionarem algum caráctere e não números.

2021-06-02 18:18 UTC, andreroggeri commented on pynubank/nubank.py
> +        if isinstance(month, inspect._empty) or isinstance(year, inspect._empty):
Eu fiz um teste aqui e deveria funcionar normalmente:

```
>>> from datetime import datetime
>>> now = datetime.now()
>>> now
datetime.datetime(2021, 6, 2, 15, 11, 13, 920905)
>>> now.year
2021
>>> now.month
6
>>> def do_something(v=datetime.now().month):
...   print(v)
...
>>> do_something()
6
>>> do_something(5)
5

2021-06-02 18:19 UTC, andreroggeri commented on pynubank/nubank.py
> +        return float(''.join(num for num in value if num.isdigit() or num == '.'))
Faz sentido, nesse caso poderia ser uma expressão regular que pega somente números e vírgulas

2021-06-02 18:21 UTC, Ulisses1478 commented on pynubank/nubank.py
> +        return float(''.join(num for num in value if num.isdigit() or num == '.'))
Sim, concordo

2021-06-02 18:44 UTC, Ulisses1478 commented on pynubank/nubank.py
> +        if isinstance(month, inspect._empty) or isinstance(year, inspect._empty):
O problema não foi no shell é quando roda o pytest

2021-06-03 22:03 UTC, andreroggeri commented on pynubank/nubank.py
> +        if isinstance(month, inspect._empty) or isinstance(year, inspect._empty):
Entendi, dei uma olhada aqui e quebra o teste `test_check_not_tested_new_methods` pq ele tenta passar os parametros de uma maneira meio _mágica_ e passa um _empty pro seu método e ele quebra.

Lá tem um objeto `default_params` que pode ser utilizado para sobrepor esse comportamento, eu commitei essa alteração na sua branch

2021-06-03 23:49 UTC, andreroggeri commented
Hmmm, utilizar mes=12 não funciona pq qdo soma 12+1 não é um mês válido =T

2021-06-04 00:05 UTC, merged